# NumPy Lab-3
Student Name:Ashish Acharya
Date:2082/02/04
Lab_on:NumPy
Lab_No:03


In [ ]:
# 1.Introduction to numpy array
import numpy as np
print("NumPy Version:",np.__version__)


NumPy Version: 2.0.2


In [ ]:
print("\n --- Basic Array Creation--")
# creating a simple 1-D array
arr1d=np.array([1,2,3,4,5])
print("1-D ArrayL",arr1d)


 --- Basic Array Creation--
1-D ArrayL [1 2 3 4 5]


In [ ]:
print("Type:",type(arr1d))

Type: <class 'numpy.ndarray'>


In [ ]:
print("Shape:",arr1d.shape)

Shape: (5,)


In [ ]:
print("Size:",arr1d.size)

Size: 5


In [ ]:
print("Data type:",arr1d.dtype)

Data type: int64


In [ ]:
# Creating a 2D array
arr2d=np.array([[1,2,3],[4,5,6]])
print("\n2D array:")
print(arr2d)


2D array:
[[1 2 3]
 [4 5 6]]


In [ ]:
print("Shape",arr2d.shape)

Shape (2, 3)


In [ ]:
# Creating a 3-D array
arr3d=np.array([[1,2],[3,4],[5,6],[7,8]])
print("\n 3D array:")
print(arr3d)



 3D array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
print("shape:",arr3d.shape)

shape: (4, 2)


In [ ]:
# Array Distribution
print("\n --- Array Attributes--")
arr=np.array([[1,2,3],[4,5,6]],dtype=np.float64)
print("Array:")
print(arr)



 --- Array Attributes--
Array:
[[1. 2. 3.]
 [4. 5. 6.]]


dtype=np.float64: This specifies the data type of the elements within the array. np.float64 indicates that each element will be a 64-bit floating-point number. Even though the initial values are integers, NumPy will store them as floating-point numbers due to this specification.

In [ ]:
print("Dimensions:",arr.ndim)

Dimensions: 2


In [ ]:
print("Shape",arr.shape)

Shape (2, 3)


In [ ]:
print("Size",arr.size)

Size 6


In [ ]:
print("Data Type:",arr.dtype)

Data Type: float64


In [ ]:
print("Element size (bytes)",arr.itemsize)

Element size (bytes) 8


arr.itemsize: This is an attribute of the NumPy array object arr. It returns an integer representing the number of bytes each individual element in the array occupies in memory. Since the array arr was created with dtype=np.float64, each element is a 64-bit floating-point number, which occupies 8 bytes (64 bits / 8 bits/byte = 8 bytes).

In [ ]:
print("Total memory used (bytes):",arr.nbytes)

Total memory used (bytes): 48



arr.size is 6 (2 rows * 3 columns).
arr.itemsize is 8 bytes (for a float64).
Therefore, arr.nbytes will be 6 * 8 = 48 bytes.


In [ ]:
from ast import Constant
# Array Creation and manipulation
print("--Array Creation and manipulation--")
#2.1 Creating special arrays
print("\n-- Special Arrays--")
# Array of zeros
zeros=np.zeros((3,4))
print("Zeros :\n ",zeros)
# Array of ones
ones=np.ones((2,3,2))
print("\n Ones:\n",ones)
# Array with a constant value
constant=np.full((2,3),7)
print("\n Constant array:\n",Constant)

--Array Creation and manipulation--

-- Special Arrays--
Zeros :
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 Ones:
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]

 Constant array:
 <class 'ast.Constant'>


### Syntax :of Zeros
numpy.zeros()
numpy.zeros(shape, dtype=float, order='C', *, like=None)

### Syntax of Ones
numpy.ones(shape, dtype=None, order='C', *, device=None, like=None)

In [ ]:
# set a seed for reprodicibility
np.random.seed(42)
# Random integers
# Use the randint function from the np.random module
rand_ints = np.random.randint(0, 10, 5)
print("Random integers (0-9):",rand_ints)
# Random floats (uniform distribution)
rand_floats=np.random.random(5)
print("Random floats (0-1)",rand_floats)
# Random floats in range
rand_range=np.random.uniform(-1,1,5)
print("Random floats(-1 to 1)",rand_range)
# 8.2 Distribution
# Normal Distribution
normal=np.random.normal(0,1,5) # mean=0 std=1
print("Normal Distribution samples:",normal)
# Binomial Distribution
binomial=np.random.normal(10,0.5,5) # n=10 p=0.5
print("Binomial Distribution samples:",binomial)
# poisson distribution
poission=np.random.poisson(3,5) # lambda=3
print("Poissiob Distribution",poission)
#8.3 Random Sampling
print("\n Random Sampling")
Population=np.arange(10)
print("Population:",Population)
# Random Choice
choices=np.random.choice(Population,5)
print("Sampled values:",choices)
# Random Choice with replacement
choices_with_replacement=np.random.choice(Population,5,replace=True)
print("Sampled values with replacement:",choices_with_replacement)

Random integers (0-9): [6 3 7 4 6]
Random floats (0-1) [0.44583275 0.09997492 0.45924889 0.33370861 0.14286682]
Random floats(-1 to 1) [ 0.30177695 -0.88717684  0.44399754  0.87710542 -0.99844247]
Normal Distribution samples: [ 0.02222183 -0.42779291 -0.53181741 -0.1174755   0.2220789 ]
Binomial Distribution samples: [ 9.61601175 10.0712323   9.98267391 10.56716963  9.94762723]
Poissiob Distribution [2 3 2 3 3]

 Random Sampling
Population: [0 1 2 3 4 5 6 7 8 9]
Sampled values: [3 5 1 9 1]
Sampled values with replacement: [9 3 7 6 8]


In [ ]:
# calculate the mean median and mode from this 2-D array:
from scipy import stats

# Creating a 2D array
arr2d=np.array([[1,2,3],[4,5,6]])
print("\n2D array:")
print(arr2d)

# Calculate mean
mean_arr2d = np.mean(arr2d)
print("Mean of the array:", mean_arr2d)

# Calculate median
median_arr2d = np.median(arr2d)
print("Median of the array:", median_arr2d)

# Calculate mode (requires scipy)
mode_arr2d = stats.mode(arr2d.flatten())
print("Mode of the array:", mode_arr2d.mode[0])

# Zips Laws inplementaion